# Generated by Django 3.2 on 2021-04-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
