# Generated by Django 3.2 on 2021-04-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nombre',
            new_name='name',
        ),
    ]
